import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Cloud API',
      link: {
        "type": "generated-index",
        "title": "Cloud API"
      },
      items: [
        'cloud-api/introduction',
        'cloud-api/authentication',
        {
          type: 'category',
          label: 'Account',
          link: {
            "type": "generated-index",
            "title": "Account"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/account'
            }
          ]
        },
        {
          type: 'category',
          label: 'Sites',
          link: {
            "type": "generated-index",
            "title": "Sites"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/sites'
            }
          ]
        },
        {
          type: 'category',
          label: 'Tiles',
          link: {
            "type": "generated-index",
            "title": "Tiles"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/tiles'
            }
          ]
        },
        {
          type: 'category',
          label: 'Lock Operations',
          link: {
            "type": "generated-index",
            "title": "Lock Operations"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/lock-operations'
            }
          ]
        },
        {
          type: 'category',
          label: 'Platform',
          link: {
            "type": "generated-index",
            "title": "Platform"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/platform'
            }
          ]
        },
        {
          type: 'category',
          label: 'Encoding',
          link: {
            "type": "generated-index",
            "title": "Encoding"
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/encoding'
            }
          ]
        },
        'cloud-api/errors'
      ]
    },

    {
      type: 'category',
      label: 'Kotlin Multiplatform SDK',
      link: {
        "type": "generated-index",
        "title": "Kotlin Multiplatform SDK"
      },
      items: [
        'kotlin-multiplatform-sdk/build',
        'kotlin-multiplatform-sdk/install',
        'kotlin-multiplatform-sdk/initialize',
        'kotlin-multiplatform-sdk/crypto',
        'kotlin-multiplatform-sdk/context-manager',
        'kotlin-multiplatform-sdk/accountless',
        'kotlin-multiplatform-sdk/account',
        'kotlin-multiplatform-sdk/fusion',
        'kotlin-multiplatform-sdk/helper',
        'kotlin-multiplatform-sdk/lock-operations',
        'kotlin-multiplatform-sdk/platform',
        'kotlin-multiplatform-sdk/sites',
        'kotlin-multiplatform-sdk/tiles',
        'kotlin-multiplatform-sdk/samples'
      ]
    },

    {
      type: 'category',
      label: 'Guides',
      link: {
        "type": "generated-index",
        "title": "Integration Guides"
      },
      items: [
        'guide/authenticating-your-users',
        'guide/ephemeral-key-registration-unlocking-a-door',
        'guide/adding-more-ephemeral-keys-secondary-authentication-checks',
        'guide/sharing-doors'
      ]
    }
  ],
};

export default sidebars;
