import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Cloud API',
      items: [
        'cloud-api/introduction',
        'cloud-api/authentication',
        {
          type: 'category',
          label: 'Account',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/account'
            }
          ]
        },
        {
          type: 'category',
          label: 'Sites',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/sites'
            }
          ]
        },
        {
          type: 'category',
          label: 'Tiles',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/tiles'
            }
          ]
        },
        {
          type: 'category',
          label: 'Lock Operations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/lock-operations'
            }
          ]
        },
        {
          type: 'category',
          label: 'Platform',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/platform'
            }
          ]
        },
        {
          type: 'category',
          label: 'Encoding',
          items: [
            {
              type: 'autogenerated',
              dirName: 'cloud-api/encoding'
            }
          ]
        },
        'cloud-api/errors'
      ]
    },
    {
      type: 'category',
      label: 'Kotlin Multiplatform SDK',
      items: [
        'kotlin-multiplatform-sdk/build',
        'kotlin-multiplatform-sdk/install'
      ]
    }
  ],
};

export default sidebars;
